{% set name = "pylatexenc" %}
{% set version = "2.7" %}
{% set sha256 = "3283163fdf130cef31532979dd766c91552ffa515f3815b8948929f37388765c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/phfaist/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - latexwalker = pylatexenc.latexwalker.__main__:main
    - latex2text = pylatexenc.latex2text.__main__:main
    - latexencode = pylatexenc.latexencode.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pylatexenc
  commands:
    - latexwalker --help
    - latex2text --help
    - latexencode --help

about:
  home: https://github.com/phfaist/pylatexenc
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple LaTeX parser providing latex-to-unicode and unicode-to-latex conversion
  doc_url: https://pylatexenc.readthedocs.io
  dev_url: https://github.com/phfaist/pylatexenc
